linux-x86_64-gcc_task:
  container:
    image: ubuntu:latest

  clone_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install git
    - git clone --recursive https://github.com/Buenia0/libblueberrn.git

  setup_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake libsdl2-dev

  matrix:
    - build_script:
        - cd libblueberrn
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_EXAMPLE="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j$(nproc --all)

macOS-x86_64-apple_task:
  macos_instance:
    image: big-sur-base

  clone_script:
    - brew install git
    - git clone --recursive https://github.com/Buenia0/libblueberrn.git

  setup_script:
    - brew install cmake pkg-config sdl2

  matrix:
    - build_script:
        - cd libblueberrn
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_EXAMPLE="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j$(sysctl -n hw.ncpu)
  