name: CMake Build (Ubuntu x86-64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cmake pkg-config libsdl2-dev
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DBUILD_EXAMPLE="ON" -DCMAKE_BUILD_TYPE="Release"
    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(nproc --all)
        mkdir -p dist
        cp example/sdl2/example dist
        mkdir -p dist/roms
        echo "Place your ROMs (in file or zip form) HERE!" > dist/roms/PLACE-ROMS-HERE.txt
    - uses: actions/upload-artifact@v1
      with:
        name: blueberrn-emu
        path: ${{runner.workspace}}/build/dist
      